site_name: Necromancer's Apprentice
theme: readthedocs
repo_url: https://github.com/shakna-israel/NecromancersApprentice
site_description: The world was born in fire. It was destroyed by ice. It was rebuilt by blood.
site_author: shakna-israel
use_directory_urls: true
pages:
- 'Home': 'index.md'
- 'Contents': 'Contents.md'
- 'License': 'LICENSE.md'
- 'Contributing': 'CONTRIBUTING.md'
- 'Prologue': '000-Chapter-Zero.md'
- 'Chapter One': '001-Chapter-One.md'
- 'Chapter Two': '002-Chapter-Two.md'
- 'Chapter Three': '003-Chapter-Three.md'
- 'Chapter Four': '004-Chapter-Four.md'
- 'Chapter Five': '005-Chapter-Five.md'
- 'Chapter Six': '006-Chapter-Six.md'
- 'Chapter Seven': '007-Chapter-Seven.md'
- 'Chapter Eight': '008-Chapter-Eight.md'
- 'Chapter Nine': '009-Chapter-Nine.md'
- 'Chapter Ten': '010-Chapter-Ten.md'
- 'Chapter Eleven': '011-Chapter-Eleven.md'
- 'Chapter Twelve': '012-Chapter-Twelve.md'
- 'Chapter Thirteen': '013-Chapter-Thirteen.md'
- 'Chapter Fourteen': '014-Chapter-Fourteen.md'
- 'Chapter Fifteen': '015-Chapter-Fifteen.md'
- 'Chapter Sixteen': '016-Chapter-Sixteen.md'
- 'Chapter Seventeen': '017-Chapter-Seventeen.md'
- 'Chapter Eighteen': '018-Chapter-Eighteen.md'
- 'Chapter Nineteen': '019-Chapter-Nineteen.md'
